[
	{ id: 218334, name: 'Strep-test', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 783, quantity: 1, code: 'U75' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217803, name: 'SZCZEPIENIE', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217780, name: 'PORADA LEKARZA POZ', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8178, quantity: 1, code: '89.00' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217779, name: 'TELEPORADA', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 9955, quantity: 1, code: '89.0099' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217783, name: 'PORADA RECEPTOWA', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8178, quantity: 1, code: '89.00' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218191, name: 'CHUK-lekarz', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217784, name: 'BILANS ZDROWIA', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218188, name: 'Edukacja przedporodowa od 32 tyg - POZ', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8193, quantity: 1, code: '89.05' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218189, name: 'Edukacja przedporodowa od 32 tyg - wada letalna', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8193, quantity: 1, code: '89.05' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218202, name: 'Zaświadczenie o niezdolności do samodzielnej egzystencji', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218187, name: 'Edukacja przedporodowa do 31 tyg.- POZ', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8193, quantity: 1, code: '89.05' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218199, name: 'Świadczenie położnej -EKUZ', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218190, name: 'Edukacja przedporodowa do 31 tyg.- wada letalna', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8193, quantity: 1, code: '89.05' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218197, name: 'Wizyta położnej po operacji ginokologicznej /onkologicznej', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217785, name: 'EKUZ', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218193, name: 'Wizyta  patronażowa - POŁOŻNA -wizyta domowa', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218194, name: 'Wizyta patronażowa - POŁOŻNA - wizyta domowa- wada letalna płodu', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218198, name: 'Świadczenie położnej - osobom z poza listy , obcokrajowcy', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218200, name: 'Świadczenie lekarza POZ - kwalifikacja do transportu dalekiego', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217800, name: 'SPOZA GMINY', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218201, name: 'Świadczenie lekarza POZ - wydanie karty DILO', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218248, name: 'gruźlica_prof', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: 5, reception_mode_choice: null },
	{ id: 218326, name: 'Ferrytyna', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 320, quantity: 1, code: 'L05' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218327, name: 'Witamina B12', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 546, quantity: 1, code: 'O83' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218328, name: 'Kwas foliowy', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 398, quantity: 1, code: 'M41' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218329, name: 'Anty-CCP', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 474, quantity: 1, code: 'N66' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218330, name: 'CRP - szybki test ilościowy (populacja do ukończenia 6 r.ż)', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218331, name: 'Przeciwciała anty-HCV', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 856, quantity: 1, code: 'V48' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217782, name: 'PORADA PATRONAŻOWA LEKARZA POZ ZREALIZOWANA W DOMU ŚWIADCZENIOBIORCY', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8178, quantity: 1, code: '89.00' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217025, name: 'PORADA PATRONAŻOWA LEKARZA POZ ZREALIZOWANA W MIEJSCU UDZIELANIA ŚWIADCZEŃ', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8178, quantity: 1, code: '89.00' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217024, name: 'PORADA LEKARSKA UDZIELONA W DOMU PACJENTA', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 8178, quantity: 1, code: '89.00' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217801, name: 'SZCZEPIENIE PRZECIWKO COVID-19', state: true, services: [], private_services: [], visittype_icd9: [], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 217802, name: 'SZCZEPIENIE PRZECIWKO HPV', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 10036, quantity: 1, code: '99.559' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218332, name: 'Antygen H. pylori w kale - test kasetkowy', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 723, quantity: 1, code: 'U15' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{ id: 218333, name: 'Antygen H. pylori w kale - test laboratoryjny', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 723, quantity: 1, code: 'U15' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null },
	{
		id: 219656,
		name: '40+ kobieta',
		state: true,
		services: [],
		private_services: [],
		visittype_icd9: [
			{ icd9: 342, quantity: 1, code: 'L43' },
			{ icd9: 9876, quantity: 1, code: '93.079' },
			{ icd9: 54, quantity: 1, code: 'C66' },
			{ icd9: 400, quantity: 1, code: 'M45' },
			{ icd9: 3, quantity: 1, code: 'A01' },
			{ icd9: 215, quantity: 1, code: 'I19' },
			{ icd9: 48, quantity: 1, code: 'C55' },
			{ icd9: 214, quantity: 1, code: 'I17' },
			{ icd9: 336, quantity: 1, code: 'L31' },
			{ icd9: 395, quantity: 1, code: 'M37' },
			{ icd9: 415, quantity: 1, code: 'M71' }
		],
		require_declaration: false,
		require_referral: true,
		visit_type_duration: 5,
		reception_mode_choice: '4'
	},
	{
		id: 219657,
		name: '40 + Men',
		state: true,
		services: [],
		private_services: [],
		visittype_icd9: [
			{ icd9: 415, quantity: 1, code: 'M71' },
			{ icd9: 238, quantity: 1, code: 'I61' },
			{ icd9: 342, quantity: 1, code: 'L43' },
			{ icd9: 9876, quantity: 1, code: '93.079' },
			{ icd9: 48, quantity: 1, code: 'C55' },
			{ icd9: 214, quantity: 1, code: 'I17' },
			{ icd9: 395, quantity: 1, code: 'M37' },
			{ icd9: 400, quantity: 1, code: 'M45' },
			{ icd9: 3, quantity: 1, code: 'A01' },
			{ icd9: 215, quantity: 1, code: 'I19' },
			{ icd9: 336, quantity: 1, code: 'L31' },
			{ icd9: 54, quantity: 1, code: 'C66' }
		],
		require_declaration: false,
		require_referral: true,
		visit_type_duration: 5,
		reception_mode_choice: '4'
	},
	{ id: 218867, name: 'PORADA LEKARZA POZ + TEST COMBO', state: true, services: [], private_services: [], visittype_icd9: [{ icd9: 10094, quantity: 1, code: 'V101' }], require_declaration: false, require_referral: false, visit_type_duration: null, reception_mode_choice: null }
];

[
	{ id: 49888, name: 'GABINET DIAGNOSTYCZNO ZABIEGOWY/ 40+', regon: '52601869400018', department_code: '56404', departmental_code_7: '004', departmental_code_8: '9450', code_5: '01', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6/12', flat_number: '3', postal_code: '87-800', city: 'WŁOCŁAWEK', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '18:00:00', mus_code: '001', kids_allowed: false },
	{ id: 49436, name: 'GABINET PIELĘGNIARKI POZ', regon: '52601869400018', department_code: '56402', departmental_code_7: '002', departmental_code_8: '0032', code_5: '01', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6', flat_number: '12', postal_code: '87-800', city: 'WŁOCŁAWEK', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '18:00:00', mus_code: '001', kids_allowed: false },
	{ id: 49437, name: 'GABINET POŁOŻNEJ POZ', regon: '52601869400018', department_code: '56403', departmental_code_7: '003', departmental_code_8: '0034', code_5: '01', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6', flat_number: '12', postal_code: '87-800', city: 'WŁOCŁAWEK', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '18:00:00', mus_code: '001', kids_allowed: false },
	{ id: 50615, name: 'PORADNIA GINEKOLOGICZNO - POŁOŻNICZA', regon: '52601869400018', department_code: '', departmental_code_7: '006', departmental_code_8: '', code_5: '02', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6/12', flat_number: '3', postal_code: '87-800', city: 'Włocławek', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '17:00:00', mus_code: '001', kids_allowed: false },
	{ id: 49435, name: 'PORADNIA LEKARZA POZ', regon: '52601869400018', department_code: '56401', departmental_code_7: '001', departmental_code_8: '0010', code_5: '01', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6', flat_number: '12', postal_code: '87-800', city: 'WŁOCŁAWEK', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '18:00:00', mus_code: '001', kids_allowed: false }
];

{ id: 49435, name: 'PORADNIA LEKARZA POZ', regon: '52601869400018', department_code: '56401', departmental_code_7: '001', departmental_code_8: '0010', code_5: '01', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6', flat_number: '12', postal_code: '87-800', city: 'WŁOCŁAWEK', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '18:00:00', mus_code: '001', kids_allowed: false }
[{"id":58155,"name":"Gabinet TELEPORAD ONLINE","department":49435},{"id":56597,"name":"PORADNIA LEKARZA POZ","department":49435}]}
{ id: 50615, name: 'PORADNIA GINEKOLOGICZNO - POŁOŻNICZA', regon: '52601869400018', department_code: '', departmental_code_7: '006', departmental_code_8: '', code_5: '02', nip: '8883163169', telephone: '544271577', street: 'Zduńska', house_number: '6/12', flat_number: '3', postal_code: '87-800', city: 'Włocławek', province: 'Kujawsko-pomorskie', country: 'POLSKA', work_from: '08:00:00', work_to: '17:00:00', mus_code: '001', kids_allowed: false },
